### PR TITLE
Added binary-search in cpp

### PR DESCRIPTION
**Pull request by KritikaTri**

### CODE REVIEW

**Comment by Coder-Jat** [comment]
image

Your code only showed one output i.e 10 ..what if we try to find another 
I attached SS of the output 
Btw I'm also new..so if i made any mistake plzz correct me without any hesitation

**Comment by KritikaTri** [comment]
Yeah, that was because I had taken a sample array of [ 2,3,4,10,40 ]  and the program printed the index of element '10'. I can change it to print the index of any random element of the array. Shall I?

**Comment by Coder-Jat** [comment]
Yaa...Sure. I also Want this in the code that's why i commented that only fixed number's location is in the result ...

**Comment by KritikaTri** [comment]
Dn..do checkout and merge my pull request.

**Pull request merged**
